### ISSUE TITLE
About depth estimation

### ISSUE THREAD

**Issue by Dawskiper** [JohanVer/SMSnet#1]
Hi, authors,

From the video example, it seems the input images are captured by monocular camera. Another thing is, in the paper, you mentioned the depth estimation is done by using DispNet. However, the DispNet requires stereo images as input. I am wonderning if there is anything wrong of my understanding.

Thanks!

**Comment by JohanVer** [comment]
Hey,

For the EFS and for the range clipping we use indeed stereo images and use
dispnet for estimating the disparity. The datasets cityscapes and KITTI do
provide the left and the right images.

Best regards,
Johan
Dawskiper <notifications@github.com> schrieb am Di. 26. Sep. 2017 um 23:04:

**Comment by Dawskiper** [comment]
Yeah that's reasonable, thank you for your explanation.
